version: 2.1
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@1.5.0
jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test
    push:
      steps:
        - setup_remote_docker
        
    
  
  
workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - push:
          requires:
            - test
